version: '3'
services:
  uati-db:
    image: postgres:9.6
    container_name: 'uati-db'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    ports:
      - 5432:5432
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    networks:
      - backend-uati
  uati-api:
    image: uati-api
    container_name: 'uati-api-test'
    depends_on:
      - 'uati-db'
    ports:
      - 8080:8080
    networks:
      - backend-uati

networks:
  backend-uati:
    driver: bridge
